### ISSUE TITLE
How to let users pick different escape character for CSV?

### ISSUE THREAD

**Issue by green-digger** [moj-analytical-services/mojap-arrow-pd-parser#14]
At the moment we have assumed the escape character is " within a csv. 

What the escape character is may differ dependent on how the csv was generated.

I think we want to add the functionality to pass key word arguments into the csv to arrow function.

**Comment by isichei** [comment]
We should add `**kwargs` into our function that just get passed down to the `pyarrow.csv` function

**Comment by AnthonyCody** [comment]
We've tested " and ' as escape characters: **"** works, **'** doesn't.
